title: Brian Hyuk Lee
# description: Everyday Life
author: Brian
avatar: /assets/portfolio.png
email: sydbne17@gmail.com
github: github.com/dlgur1994
linkedin: www.linkedin.com/in/brian-hyuk-lee-
instagram: www.instagram.com/hyuk.b.l17

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5

# Uncomment the below line and set the tracking ID for enabling Google Analytics
#
# google_analytics:

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
#
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: /assets/portfolio.png
social:
  name: Brian
  links:
    - https://www.linkedin.com/in/brian-hyuk-lee-
    - https://github.com/ngzhio
    - https://www.instagram.com/hyuk.b.l17
# google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
